### PR TITLE
Add basic support for linting / format🐍

### PR DESCRIPTION
**Pull request by KarelZe**
This PR adds basic support for linting/formatting based on [ruff](https://docs.astral.sh/), as discussed in #23 .

A minimal rule set (see `pyproject.toml`) is appied to keep diff in PR small. More rules can be added from https://beta.ruff.rs/docs/rules/. Currently, `I` isort is used for sorting imports, pep8-naming `N` for naming conventions, `NPY` for Numpy best practices, and `RUF` for ruff-specific rules. You can also ignore rules, either in the `pyproject.toml`, as done for all lower-case variable names, which contradicts matrix naming conventions or on the code level e.g., `# noqa: N802`, as done in `kernel_estimator.py` for function_names due to the same reason.

We should verify that the changes from refactoring / update of numpy random number generation, didn't break anything. Will keep this as WIP until I've performed some tests 🤓

@iancovert Do you want additional rules / different configurations?

### CODE REVIEW

**Comment by iancovert** [comment]
All the ruff related changes look good to me!

For the random number generation, it looks like this was in just a couple places, right? I think the refactoring in `iterated_estimator.py` makes sense, but it could be better add a `random_state` argument to the constructor with a default argument. And the change in `utils.py` might be a problem, because the `sample_subset_feature` helper function would now return the same values every time. I think the correct solution is to make the random state an argument to `sample_subset_feature`, and adjust the two places where it's currently used (`iterated_estimator.py` and `sign_estimator.py`) to use their `self.rng`.

**Comment by KarelZe** [comment]
@iancovert Thanks for your feedback. I noticed the same behaviour for `sample_subset_feature(...)`. This needs a fix. 🐛  Will also set `random_state` as a default argument.

Will update this PR and answer to #24 later this week. 👍

**Comment by KarelZe** [comment]
@iancovert After thinking about it again, I decided to revert my changes with regard to `numpy.random` and disable the rule `NPY002`, as it could slightly change the results extimated by the package. I think such a change should not be introduced in a linter/formatter PR and rather be adressed separately. Hope this is fine. 😊

From my point of view, PR is ready for review.

**Comment by iancovert** [comment]
Good call, that makes sense to me. I'll go ahead and merge the PR. Thanks again for adding this!

**Pull request merged**
